#!/bin/bash

########################################################################################
#
#  Copyright (c) 2022-2023 PUFsecurity and/or its affiliates. All Rights Reserved.
#
#######################################################################################

#######################################################################################
#
# File: get_random_2
#
#       API to get a x-byte random number and its signature from PUFsecurity' FPGA board.
#       x : 1-65535
#
#       Example to get 65535 random bytes:
#       http://172.16.1.132:8080/cgi-bin/get_random_2?65535
#
# History:
#
# 2022/11/08  v1.1.0    First release
# 2023/06/01  v1.2.0    Add flock protection
#
#######################################################################################


echo "Content-type:application/json"
echo


INPUT=${QUERY_STRING}
echo "Random bytes input: $INPUT"

if [$INPUT == ""]; then
    RN_BYTE=8
else
    RN_BYTE=$INPUT
fi


# PUFS utility path
PUFS_UTIL_PATH=/home/root/projects/pufs_util

PID=$$
OUT_FILE=get_random_$PID.txt
TMP_FILE=tmp_$PID.txt
LOCK_FILE=fpga.lock

flock $LOCK_FILE $PUFS_UTIL_PATH/pufs_utility -R 2 -l $RN_BYTE -a ECDSAP256 -O $OUT_FILE > $TMP_FILE
rm $TMP_FILE
cat $OUT_FILE
rm $OUT_FILE
